### ISSUE TITLE
Disclosure Indicator 삭제 이유

### ISSUE THREAD

**Issue by lingostar** [uudquark/noo6#14]
https://github.com/uudquark/noo6/blob/7d65ba0c46120612dcf19ce72f291dd94c9ac0fb/Noo6Main/CategoryList.swift#L19-L20

Disclosure Indicator는 리스트에서 선택시 자세한 정보가 있다는 것을 알리는 UI적인 약속입니다.

단지 보기 싫다는 이유로 디자인 시스템을 헝크러트리는 거라면 다시 생각해 주세요.

**Comment by JaewoongLee-swift** [comment]
개인적인 디자인 욕심으로 UI가 주는 정보와 약속을 무시하려했던것 같습니다. 링고의 말씀대로 다시 Disclosure Indicator가 나타나도록 수정하였습니다!
