### ISSUE TITLE
HonorView -> HonorDetailView 이동 시 NavigationBar 중첩 오류

### ISSUE THREAD

**Issue by JaewoongLee-swift** [uudquark/noo6#21]
![Simulator Screen Shot - iPhone 13 - 2022-04-11 at 14 14 58](https://user-images.githubusercontent.com/83946704/162669338-9d4fba3b-8184-4820-8cc6-aa4464d5d1b2.png)

HonorView에서 HonorDetailView로 이동 시 NavigationBar가 중첩되어 나타나는 현상이 있습니다. HonorView에서 새로운 NavigationView를 만들어서 생긴 오류 같습니다. NavigationView만 제거해주면 간단히 해결될 것 같습니다.

**Comment by uudquark** [comment]
넵 제거했습니다~
